# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06server\"\'\n\x10HeartbeatRequest\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\"%\n\x11HeartbeatResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\"\x1d\n\nLogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32V\n\x10HeartbeatService\x12\x42\n\x0b\x43heckStatus\x12\x18.server.HeartbeatRequest\x1a\x19.server.HeartbeatResponse2D\n\x0eLoggingService\x12\x32\n\x07SendLog\x12\x12.server.LogRequest\x1a\x13.server.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=25
  _globals['_HEARTBEATREQUEST']._serialized_end=64
  _globals['_HEARTBEATRESPONSE']._serialized_start=66
  _globals['_HEARTBEATRESPONSE']._serialized_end=103
  _globals['_LOGREQUEST']._serialized_start=105
  _globals['_LOGREQUEST']._serialized_end=134
  _globals['_LOGRESPONSE']._serialized_start=136
  _globals['_LOGRESPONSE']._serialized_end=166
  _globals['_HEARTBEATSERVICE']._serialized_start=168
  _globals['_HEARTBEATSERVICE']._serialized_end=254
  _globals['_LOGGINGSERVICE']._serialized_start=256
  _globals['_LOGGINGSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
